#!/bin/bash
set -x

cd /lfs/h2/emc/vpppg/noscrub/$USER/EVS/dev/drivers/scripts/plots/global_det
rm -f jevs_global_det_atmos_grid2*_plots_*days_00.o*
qsub jevs_global_det_atmos_grid2grid_pres_levs_plots_last31days.sh
qsub jevs_global_det_atmos_grid2grid_pres_levs_plots_last90days.sh
qsub jevs_global_det_atmos_grid2grid_precip_plots_last31days.sh
qsub jevs_global_det_atmos_grid2grid_precip_plots_last90days.sh
qsub jevs_global_det_atmos_grid2grid_snow_plots_last31days.sh
qsub jevs_global_det_atmos_grid2grid_snow_plots_last90days.sh
qsub jevs_global_det_atmos_grid2grid_sst_plots_last31days.sh
qsub jevs_global_det_atmos_grid2grid_sst_plots_last90days.sh
qsub jevs_global_det_atmos_grid2grid_sea_ice_plots_last31days.sh
qsub jevs_global_det_atmos_grid2grid_sea_ice_plots_last90days.sh
qsub jevs_global_det_atmos_grid2grid_means_plots_last31days.sh
qsub jevs_global_det_atmos_grid2grid_means_plots_last90days.sh
qsub jevs_global_det_atmos_grid2obs_pres_levs_plots_last31days.sh
qsub jevs_global_det_atmos_grid2obs_pres_levs_plots_last90days.sh
qsub jevs_global_det_atmos_grid2obs_sfc_plots_last31days.sh
qsub jevs_global_det_atmos_grid2obs_sfc_plots_last90days.sh
qsub jevs_global_det_atmos_grid2obs_ptype_plots_last31days.sh
qsub jevs_global_det_atmos_grid2obs_ptype_plots_last90days.sh
qsub jevs_global_det_atmos_headline_plots.sh
